import { InvoiceFormData, InvoiceFormItem } from '../types';

export const createBlankInvoiceItem = (): InvoiceFormItem => ({
  item_name: '',
  supplier_item_name: '',
  hsn: '24022090',
  qty: 1,
  quantity: 1,
  uom: 'PAC',
  mrp_rsp: 0,
  pack_qty: 100,
  invoice_amount: 0,
  each_pack_rate: 0,
  purchase_rate: 0,
  gst_rate: 40,
  taxable_value: 0,
  cgst: 0,
  sgst: 0,
  igst: 0,
  total: 0,
  confidence: 1.0,
  needs_review: false,
  validation: { valid: true, warnings: [] },
});

export const createBlankInvoice = (): InvoiceFormData => ({
  supplier_name: 'AYYAPPA ENTERPRISES',
  supplier_gstin: '33AABFA2949R1Z5',
  invoice_number: `INV-${new Date().toISOString().slice(0, 10).replace(/-/g, '')}-${Math.floor(1000 + Math.random() * 9000)}`,
  invoice_date: new Date().toISOString().slice(0, 10),
  payment_mode: 'CASH',
  payment_status: 'PAID',
  cheque_date: new Date().toISOString().slice(0, 10),
  subtotal: 0,
  taxable_amount: 0,
  cgst: 0,
  sgst: 0,
  igst: 0,
  total_tax: 0,
  round_off: 0,
  grand_total: 0,
  items: [createBlankInvoiceItem()],
});
